[[songs]]
title = "Waterloo"
artist = "ABBA"
year = 1974
link = "www.hitstergame.com/nl/00030"

[[songs]]
title = "Die Biene Maja"
artist = "Karel Gott"
year = 1975
link = "www.hitstergame.com/de/aaaa0007/00188"

[[songs]]
title = "Hurricane"
artist = "Bob Dylan"
year = 1975
link = "www.hitstergame.com/de/aaaa0054/00055"

[[songs]]
title = "Ein Bett Im Kornfeld"
artist = "Jürgen Drews"
year = 1976
link = "www.hitstergame.com/de/00298"

[[songs]]
title = "Junge"
artist = "Die Ärzte"
year = 2007
link = "www.hitstergame.com/de/00167"

[[songs]]
title = "DJ Got Us Fallin' In Love"
artist = "Usher (feat. Pitbull)"
year = 2010
link = "www.hitstergame.com/de/aaaa0054/00254"

[[songs]]
title = "Waka Waka (This Time for Africa) ft. Freshlyground"
artist = "Shakira"
year = 2010
link = "www.hitstergame.com/de/00285"

[[songs]]
title = "Sweat (A La La La La Long)"
artist = "Inner Circle"
year = 2010
link = "www.hitstergame.com/fr/aaaa0031/00137"

[[songs]]
title = "Hangover"
artist = "Taio Cruz, Flo Rida"
year = 2011
link = "www.hitstergame.com/de/00006"

[[songs]]
title = "Moves Like Jagger"
artist = "Maroon 5, Christina Aguilera"
year = 2011
link = "www.hitstergame.com/de/00150"

[[songs]]
title = "P!nk"
artist = "Cover Me In Sunshine"
year = 2021
link = "www.hitstergame.com/pl/aaae0004/00292"

[[songs]]
title = "Solo Para Ti"
artist = "Alvaro Soler"
year = 2022
link = "www.hitstergame.com/de/aaaa0012/00177"
